// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thumb-event.proto

package top.liuqiao.thumb.protobuf.entity;

public final class ThumbEventProto {
  private ThumbEventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_top_liuqiao_thumb_listener_thumb_msg_ThumbEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_top_liuqiao_thumb_listener_thumb_msg_ThumbEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021thumb-event.proto\022$top.liuqiao.thumb.l" +
      "istener.thumb.msg\"\255\001\n\nThumbEvent\022\017\n\007user" +
      "_id\030\001 \001(\003\022\017\n\007item_id\030\002 \001(\003\022H\n\004type\030\003 \001(\016" +
      "2:.top.liuqiao.thumb.listener.thumb.msg." +
      "ThumbEvent.EventType\022\022\n\nevent_time\030\004 \001(\003" +
      "\"\037\n\tEventType\022\010\n\004INCR\020\000\022\010\n\004DECR\020\001B6\n!top" +
      ".liuqiao.thumb.protobuf.entityB\017ThumbEve" +
      "ntProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_top_liuqiao_thumb_listener_thumb_msg_ThumbEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_top_liuqiao_thumb_listener_thumb_msg_ThumbEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_top_liuqiao_thumb_listener_thumb_msg_ThumbEvent_descriptor,
        new java.lang.String[] { "UserId", "ItemId", "Type", "EventTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
