// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thumb-event.proto

package top.liuqiao.thumb.protobuf.entity;

/**
 * Protobuf type {@code top.liuqiao.thumb.listener.thumb.msg.ThumbEvent}
 */
public final class ThumbEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:top.liuqiao.thumb.listener.thumb.msg.ThumbEvent)
    ThumbEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ThumbEvent.newBuilder() to construct.
  private ThumbEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ThumbEvent() {
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ThumbEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return top.liuqiao.thumb.protobuf.entity.ThumbEventProto.internal_static_top_liuqiao_thumb_listener_thumb_msg_ThumbEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return top.liuqiao.thumb.protobuf.entity.ThumbEventProto.internal_static_top_liuqiao_thumb_listener_thumb_msg_ThumbEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            top.liuqiao.thumb.protobuf.entity.ThumbEvent.class, top.liuqiao.thumb.protobuf.entity.ThumbEvent.Builder.class);
  }

  /**
   * <pre>
   * 事件类型枚举
   * </pre>
   *
   * Protobuf enum {@code top.liuqiao.thumb.listener.thumb.msg.ThumbEvent.EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 点赞
     * </pre>
     *
     * <code>INCR = 0;</code>
     */
    INCR(0),
    /**
     * <pre>
     * 取消点赞
     * </pre>
     *
     * <code>DECR = 1;</code>
     */
    DECR(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 点赞
     * </pre>
     *
     * <code>INCR = 0;</code>
     */
    public static final int INCR_VALUE = 0;
    /**
     * <pre>
     * 取消点赞
     * </pre>
     *
     * <code>DECR = 1;</code>
     */
    public static final int DECR_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return INCR;
        case 1: return DECR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.liuqiao.thumb.protobuf.entity.ThumbEvent.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:top.liuqiao.thumb.listener.thumb.msg.ThumbEvent.EventType)
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  private long userId_;
  /**
   * <pre>
   * 用户ID
   * </pre>
   *
   * <code>int64 user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int ITEM_ID_FIELD_NUMBER = 2;
  private long itemId_;
  /**
   * <pre>
   * 博客ID
   * </pre>
   *
   * <code>int64 item_id = 2;</code>
   * @return The itemId.
   */
  @java.lang.Override
  public long getItemId() {
    return itemId_;
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <pre>
   * 事件类型
   * </pre>
   *
   * <code>.top.liuqiao.thumb.listener.thumb.msg.ThumbEvent.EventType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * 事件类型
   * </pre>
   *
   * <code>.top.liuqiao.thumb.listener.thumb.msg.ThumbEvent.EventType type = 3;</code>
   * @return The type.
   */
  @java.lang.Override public top.liuqiao.thumb.protobuf.entity.ThumbEvent.EventType getType() {
    @SuppressWarnings("deprecation")
    top.liuqiao.thumb.protobuf.entity.ThumbEvent.EventType result = top.liuqiao.thumb.protobuf.entity.ThumbEvent.EventType.valueOf(type_);
    return result == null ? top.liuqiao.thumb.protobuf.entity.ThumbEvent.EventType.UNRECOGNIZED : result;
  }

  public static final int EVENT_TIME_FIELD_NUMBER = 4;
  private long eventTime_;
  /**
   * <pre>
   * 事件发生时间
   * </pre>
   *
   * <code>int64 event_time = 4;</code>
   * @return The eventTime.
   */
  @java.lang.Override
  public long getEventTime() {
    return eventTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (itemId_ != 0L) {
      output.writeInt64(2, itemId_);
    }
    if (type_ != top.liuqiao.thumb.protobuf.entity.ThumbEvent.EventType.INCR.getNumber()) {
      output.writeEnum(3, type_);
    }
    if (eventTime_ != 0L) {
      output.writeInt64(4, eventTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (itemId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, itemId_);
    }
    if (type_ != top.liuqiao.thumb.protobuf.entity.ThumbEvent.EventType.INCR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    if (eventTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, eventTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof top.liuqiao.thumb.protobuf.entity.ThumbEvent)) {
      return super.equals(obj);
    }
    top.liuqiao.thumb.protobuf.entity.ThumbEvent other = (top.liuqiao.thumb.protobuf.entity.ThumbEvent) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (getItemId()
        != other.getItemId()) return false;
    if (type_ != other.type_) return false;
    if (getEventTime()
        != other.getEventTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + ITEM_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getItemId());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + EVENT_TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEventTime());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(top.liuqiao.thumb.protobuf.entity.ThumbEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code top.liuqiao.thumb.listener.thumb.msg.ThumbEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:top.liuqiao.thumb.listener.thumb.msg.ThumbEvent)
      top.liuqiao.thumb.protobuf.entity.ThumbEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.liuqiao.thumb.protobuf.entity.ThumbEventProto.internal_static_top_liuqiao_thumb_listener_thumb_msg_ThumbEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.liuqiao.thumb.protobuf.entity.ThumbEventProto.internal_static_top_liuqiao_thumb_listener_thumb_msg_ThumbEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.liuqiao.thumb.protobuf.entity.ThumbEvent.class, top.liuqiao.thumb.protobuf.entity.ThumbEvent.Builder.class);
    }

    // Construct using top.liuqiao.thumb.protobuf.entity.ThumbEvent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = 0L;

      itemId_ = 0L;

      type_ = 0;

      eventTime_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return top.liuqiao.thumb.protobuf.entity.ThumbEventProto.internal_static_top_liuqiao_thumb_listener_thumb_msg_ThumbEvent_descriptor;
    }

    @java.lang.Override
    public top.liuqiao.thumb.protobuf.entity.ThumbEvent getDefaultInstanceForType() {
      return top.liuqiao.thumb.protobuf.entity.ThumbEvent.getDefaultInstance();
    }

    @java.lang.Override
    public top.liuqiao.thumb.protobuf.entity.ThumbEvent build() {
      top.liuqiao.thumb.protobuf.entity.ThumbEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public top.liuqiao.thumb.protobuf.entity.ThumbEvent buildPartial() {
      top.liuqiao.thumb.protobuf.entity.ThumbEvent result = new top.liuqiao.thumb.protobuf.entity.ThumbEvent(this);
      result.userId_ = userId_;
      result.itemId_ = itemId_;
      result.type_ = type_;
      result.eventTime_ = eventTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof top.liuqiao.thumb.protobuf.entity.ThumbEvent) {
        return mergeFrom((top.liuqiao.thumb.protobuf.entity.ThumbEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(top.liuqiao.thumb.protobuf.entity.ThumbEvent other) {
      if (other == top.liuqiao.thumb.protobuf.entity.ThumbEvent.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getItemId() != 0L) {
        setItemId(other.getItemId());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getEventTime() != 0L) {
        setEventTime(other.getEventTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readInt64();

              break;
            } // case 8
            case 16: {
              itemId_ = input.readInt64();

              break;
            } // case 16
            case 24: {
              type_ = input.readEnum();

              break;
            } // case 24
            case 32: {
              eventTime_ = input.readInt64();

              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private long userId_ ;
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户ID
     * </pre>
     *
     * <code>int64 user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private long itemId_ ;
    /**
     * <pre>
     * 博客ID
     * </pre>
     *
     * <code>int64 item_id = 2;</code>
     * @return The itemId.
     */
    @java.lang.Override
    public long getItemId() {
      return itemId_;
    }
    /**
     * <pre>
     * 博客ID
     * </pre>
     *
     * <code>int64 item_id = 2;</code>
     * @param value The itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemId(long value) {
      
      itemId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 博客ID
     * </pre>
     *
     * <code>int64 item_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemId() {
      
      itemId_ = 0L;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <pre>
     * 事件类型
     * </pre>
     *
     * <code>.top.liuqiao.thumb.listener.thumb.msg.ThumbEvent.EventType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 事件类型
     * </pre>
     *
     * <code>.top.liuqiao.thumb.listener.thumb.msg.ThumbEvent.EventType type = 3;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件类型
     * </pre>
     *
     * <code>.top.liuqiao.thumb.listener.thumb.msg.ThumbEvent.EventType type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public top.liuqiao.thumb.protobuf.entity.ThumbEvent.EventType getType() {
      @SuppressWarnings("deprecation")
      top.liuqiao.thumb.protobuf.entity.ThumbEvent.EventType result = top.liuqiao.thumb.protobuf.entity.ThumbEvent.EventType.valueOf(type_);
      return result == null ? top.liuqiao.thumb.protobuf.entity.ThumbEvent.EventType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 事件类型
     * </pre>
     *
     * <code>.top.liuqiao.thumb.listener.thumb.msg.ThumbEvent.EventType type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(top.liuqiao.thumb.protobuf.entity.ThumbEvent.EventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件类型
     * </pre>
     *
     * <code>.top.liuqiao.thumb.listener.thumb.msg.ThumbEvent.EventType type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private long eventTime_ ;
    /**
     * <pre>
     * 事件发生时间
     * </pre>
     *
     * <code>int64 event_time = 4;</code>
     * @return The eventTime.
     */
    @java.lang.Override
    public long getEventTime() {
      return eventTime_;
    }
    /**
     * <pre>
     * 事件发生时间
     * </pre>
     *
     * <code>int64 event_time = 4;</code>
     * @param value The eventTime to set.
     * @return This builder for chaining.
     */
    public Builder setEventTime(long value) {
      
      eventTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件发生时间
     * </pre>
     *
     * <code>int64 event_time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventTime() {
      
      eventTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:top.liuqiao.thumb.listener.thumb.msg.ThumbEvent)
  }

  // @@protoc_insertion_point(class_scope:top.liuqiao.thumb.listener.thumb.msg.ThumbEvent)
  private static final top.liuqiao.thumb.protobuf.entity.ThumbEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new top.liuqiao.thumb.protobuf.entity.ThumbEvent();
  }

  public static top.liuqiao.thumb.protobuf.entity.ThumbEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ThumbEvent>
      PARSER = new com.google.protobuf.AbstractParser<ThumbEvent>() {
    @java.lang.Override
    public ThumbEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ThumbEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ThumbEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public top.liuqiao.thumb.protobuf.entity.ThumbEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

